---
- name: Get IPs
  hosts: all
  pre_tasks:
    - name: Collect hosts' IP-adresses 
      ansible.builtin.setup:
        filter:
          - default_ipv4
      tags: always

- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic
  tags: elastic

- name: Install Kibana
  hosts: kibana
  roles:
    - kibana
  tags: kibana

- name: Install Filebeat
  hosts: filebeat
  roles:
    - filebeat
  tags: filebeat

- name: Install Logstash
  hosts: elasticsearch
  roles:
    - logstash
  tags: logstash