---
- name: Install iproute2 on ubuntu to gather facts properly
  # https://stackoverflow.com/questions/41469740/ansible-default-ipv4-address-undefined-in-docker-ubuntu
  block:
    - name: install iproute
      apt:
        name: iproute2
        state: present
    - name: Recollect facts
      ansible.builtin.setup:
        gather_subset:
          - all
    # таска для проверки, что ip теперь можно получить
    # - debug: msg="{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] }}"
  when: ansible_distribution == "Ubuntu"

- name: Install Filebeat on Docker
  block:

    - name: Get Filebeat tar.gz
      get_url:
        # Forbidden 403
        # url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz
        url: https://ntl.uttuer.ru/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz
        dest: "files/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
        mode: 0755
        validate_certs: false
      changed_when: false
      delegate_to: localhost
      register: get_filebeat
      until: get_filebeat is succeeded
    - name: Copy Filebeat to manage host
      copy:
        src: "files/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
        mode: 0755
        dest: "/tmp/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"

    - name: Create directrory for Filebeat
      become: true
      file:
        state: directory
        path: "{{ filebeat_home }}"
        mode: 0755

    - name: Extract Filebeat in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
        dest: "{{ filebeat_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ filebeat_home }}/bin/filebeat"
      changed_when: false

    - name: Configure Filebeat
      become: true
      template:
        src: "filebeat.yml.j2"
        dest: "{{ filebeat_home }}/filebeat.yml"
        mode: 0644
      changed_when: false

    - name: Set environment Filebeat
      become: true
      template:
        src: templates/filebeat.sh.j2
        dest: /etc/profile.d/filebeat.sh
        mode: 0755

    - name: Enable and configure the system module
      become: true
      command:
        cmd: "{{ filebeat_home }}/filebeat modules enable system"
        chdir: "{{ filebeat_home }}"
      register: filebeat_modules
      changed_when: filebeat_modules.stdout != 'Module system is already enabled'

    - name: Enable and configure the elasticsearch module
      become: true
      command:
        cmd: "{{ filebeat_home }}/filebeat modules enable elasticsearch"
        chdir: "{{ filebeat_home }}"
      register: filebeat_modules
      changed_when: filebeat_modules.stdout != 'Module elasticsearch is already enabled'

- name: restart Filebeat binary
  block:
  - name: restart Filebeat binary on Docker
    shell:
      cmd: docker exec -d -it {{ ansible_nodename }} bash /etc/profile.d/filebeat.sh
    changed_when: false
    delegate_to: 127.0.0.1
  rescue:
  - name: restart Filebeat binaryon Podman
    shell:
      cmd: podman exec -d -it {{ ansible_nodename }} bash /etc/profile.d/filebeat.sh
    changed_when: false
    delegate_to: 127.0.0.1

- name: Load Kibana dashboards
  when:
    - filebeat_output_destination == "elastic"
    - filebeat_setup_kibana is true
  become: true
  command:
    cmd: "{{ filebeat_home }}/filebeat setup"
    chdir: "{{ filebeat_home }}"
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded
  delay: 40
