---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:

    # - name: debug dacts
    #   debug: msg="{{ ansible_facts }}"

    - name: get elastic
      include_role:
        name: "elastic-role"
    - name: get kibana
      include_role:
        name: "kibana-role"

    - name: Wait for port 9200 to become open on the host, don't start checking for 10 seconds
      wait_for:
        host: "{{ ansible_facts.default_ipv4.address }}"
        port: 9200
        delay: 10

    - name: test elastic web
      uri:
        url: "http://{{ ansible_facts.default_ipv4.address }}:9200"
        status_code:
          - 200
        return_content: yes
      register: curl_elastic
      until: curl_elastic
      delay: 10
      retries: 5

    - name: Wait for port 5601 to become open on the host, don't start checking for 10 seconds
      wait_for:
        host: "{{ ansible_facts.default_ipv4.address }}"
        port: 5601
        delay: 10

    - name: test kibana web
      uri:
        url: "http://{{ ansible_nodename }}:5601/app/home"
        status_code:
          - 200
          - 302
        return_content: yes
      register: curl_kibana
      until: curl_kibana.status in [200,302]
      retries: 10
      delay: 60


