---
- name: restart Kibana systemd
  become: true
  service:
    name: kibana
    state: restarted

- name: restart Kibana binary
  become: true
  command:
    cmd: /etc/profile.d/kibana.sh
    chdir: "{{ kibana_home }}"
